### ISSUE TITLE
已读数量统计问题

### ISSUE THREAD

**Issue by Rhinocros** [xCss/Valine-docs#15]
在single页面可以正常统计阅读数，但是在文章列表页面就不会正常回填阅读数，代码是直接复制single页面的

**Comment by xCss** [comment]
在列表页需要初始化一下`Valine`，并确保列表页的`阅读数元素`存在

```
new Valine({
    // ...
})
```

**Comment by Rhinocros** [comment]
感谢指导，现在可以显示数量了
但是我改过标题，跟single页面的数字对不上，列表页面是按新标题重新统计的，有什么办法能直接读single的阅读数回填吗，或者我把path改成window.location.href可以正常显示吗？  会有什么问题发生？
我的URL没有变过

不太理解这句

> II. 如果值为window.location.href，可能会出现随便加不同参数进入该页面，而被判断成新页面的情况。

**Comment by xCss** [comment]
- 如果你用的是默认配置，那么`path`是`window.location.path`，不确定你的`single`页面是使用何种方式配置`path`的。

- 目前`阅读数`统计是根据`window.location.path`来对比`目标元素`中的`id`，如果相同，则阅读数+1，如果不同则只显示

- 如果你想显示阅读数，请确认`Valine`初始化的时候`path`是`window.location.path`，而不是其他选项


---------------
我的A页面是`http://xxx.com/a.page`，A页面当前有10条评论，如果加了参数变成`http://xxx.com/a.page?p=1`那么：
- 此时如果`path`是`window.location.path`，则`path=/a.page`，页面不变，评论数不变
- 此时如果`path`是`window.location.href`，则`path=http://xxx.com/a.page?p=1`，页面不变，但参数变化，被判断为新页面，评论数为0

**Comment by Rhinocros** [comment]
初始化时没有配置path，应该是默认的，而且我的是静态站，没有参数变化
您可以受累看一下www.digit77.com    首页列表显示有的就和single数字就不一样，但是页面地址没有任何参数，是一样的
只不过有的改过标题，比如置顶第一个，没改过的就没问题，比如置顶第五个
改过标题的就对不上了

**Comment by xCss** [comment]
看了一下，发现你的数据有点不正常，出现了3条相同的数据，但是time却不同，你去leancloud后台筛选下，删掉重复的数据试试~
![image](https://user-images.githubusercontent.com/10877162/56413292-96cd0080-62b9-11e9-8dfe-96452d7ead4b.png)

**Comment by Rhinocros** [comment]
确实删掉重复数据就好了，非常感谢
