### ISSUE TITLE
请问在next中怎么设置评论区背景色

### ISSUE THREAD

**Issue by Monster0303** [xCss/Valine-docs#17]
我用的next
尝试了加入了
 //valine评论背景色
.v .vwrap .vcard {
    background:rgba(255 255 255,80%) none repeat scroll !important;
}

但是没有效果啊

**Comment by upupupfly** [comment]
> 我用的next
> 尝试了加入了
> //valine评论背景色
> .v .vwrap .vcard {
> background:rgba(255 255 255,80%) none repeat scroll !important;
> }
> 
> 但是没有效果啊

![image](https://user-images.githubusercontent.com/23210602/69128172-bc87e580-0ae6-11ea-84dd-12e9a5312f51.png)
你的css样式有误
