### ISSUE TITLE
为什么评论了之后只显示头像

### ISSUE THREAD

**Issue by dymyw** [xCss/Valine-docs#21]
![image](https://user-images.githubusercontent.com/6252582/61854336-7338d800-aef0-11e9-8b1a-a807df793102.png)

官网下的评论就没有

**Comment by xCss** [comment]
??? 预览地址

**Comment by xCss** [comment]
换个浏览器试试~

**Comment by dymyw** [comment]
https://valine.js.org/ 用 Safari 可以，用 Chrome 居然不行

**Comment by xCss** [comment]
看看控制台报什么错~

**Comment by dymyw** [comment]
![image](https://user-images.githubusercontent.com/6252582/61855103-045c7e80-aef2-11e9-875b-16c4e0b4fbaa.png)

**Comment by xCss** [comment]
额，会审核代码吗，看看元素是否存在。。。

目测是你浏览器渲染出问题了

**Comment by dymyw** [comment]
我也觉得是我电脑 Chrome 的问题，重新安装试试
