### ISSUE TITLE
好像pjax加载的页面显示有点问题.

### ISSUE THREAD

**Issue by xunni1000** [xCss/Valine-docs#4]
不知道是不是我页面哪里没有写好.

入口页面
https://www.yge.me/public/addons/yakeblog/detail/show/id/10.html
有两条测试评论,没毛病.

然后,
页面底部有下一页或者上一页.
点一点.  会pjax载入另外一页.

会在上一页(id/11) 或者下一页(id/9) 显示 id/10的评论.

如果直接打开(id/11)  或者(id/9)  显示都是正常的.
是不是我应该监控dom变化,然后再初始化?

**Comment by xCss** [comment]
关于pjax加载评论失败是个已知bug~~~ [#66](https://github.com/xCss/Valine/issues/66)
![exx y7vmc ib 1e4q clv1](https://user-images.githubusercontent.com/10877162/46987618-9051a680-d127-11e8-9a36-2eb4741dc962.jpg)

**Comment by xunni1000** [comment]
参考了#66的方法,对我来说不太好使,方法没错,主要是我的js文件有问题,会导致评论出现两次.
后面再研究研究了下.
居然莫名解决了.




原来直接是
 new Valine({参数})
现在莫名加一个
var valine =  new Valine({参数})
完美解决
代码如下,放在footer.html , 在jquery等JS文件后面 
`
<script>
    var valine = new Valine({
        el: '#disqus_thread',
        appId: '5dYP3JNvqQNYSglzKFtDnyjb-gzGzoHsz',
        appKey: 'kciuqExfaRVV0Pxi9kHeMnbl',
		placeholder:'放码过来~',
		notify:true,
		verify:true,
		path:window.location.pathname,
		pageSize:10
    })
</script>
`

引用文件放在meat.html中,没加data-no-instant
<script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script>
<script src='//cdn.jsdelivr.net/npm/valine@1.3.3/dist/Valine.min.js'></script>



好神奇,好意外

**Comment by xCss** [comment]
优秀 优秀~~
