### ISSUE TITLE
为什么访问官方文档，我的mac电脑cpu负载直接飙升

### ISSUE THREAD

**Issue by lbyworkspace** [xCss/Valine-docs#65]
我查看了F12的内存，一直在下载资源
<img width="761" alt="image" src="https://user-images.githubusercontent.com/89441249/159195420-4fefd421-17e0-4e5c-a071-f78bc5a978ee.png">

**Comment by xCss** [comment]
> 我查看了F12的内存，一直在下载资源 <img alt="image" width="761" src="https://user-images.githubusercontent.com/89441249/159195420-4fefd421-17e0-4e5c-a071-f78bc5a978ee.png">

收到，我这边自查下，感谢反馈~

**Comment by lbyworkspace** [comment]
昨天新买的macbook M1芯片的，今天访问你的文档突然风扇转的特别大声，我还以为我的电脑出问题了

**Comment by xCss** [comment]
> 昨天新买的macbook M1芯片的，今天访问你的文档突然风扇转的特别大声，我还以为我的电脑出问题了

已确认是xss漏洞，已在[v1.4.18](https://github.com/xCss/Valine/releases/tag/v1.4.18)修复，感谢反馈~ 👍

**Comment by lbyworkspace** [comment]
没事，举手之劳而已

**Comment by lemontree2000** [comment]
> 




> > 昨天新买的macbook M1芯片的，今天访问你的文档突然风扇转的特别大声，我还以为我的电脑出问题了
> 
> 已确认是xss漏洞，已在[v1.4.18](https://github.com/xCss/Valine/releases/tag/v1.4.18)修复，感谢反馈~ 👍

可以把那个xss攻击的评论删了嘛

<img width="837" alt="image" src="https://user-images.githubusercontent.com/21957062/168338833-ede582e4-d671-4679-ac17-fbdb07597959.png">
