### ISSUE TITLE
gravatar头像在国内无法显示

### ISSUE THREAD

**Issue by Raydon10** [xCss/Valine-docs#69]
<img width="541" alt="image" src="https://user-images.githubusercontent.com/39195322/198220780-9add1046-cf13-4e94-93bd-44aa916d3316.png">

**Comment by xCss** [comment]
初始化配置的时候，可以自定义`gravatar`头像源：
``` js
new Valine({
    avatar_cdn: 'https://cravatar.cn/avatar/', // or https://cdn.sep.cc/avatar/ or https://gravatar.kuibu.net/avatar/
    // your other config
})
```
