### ISSUE TITLE
Hexo Aurora 主题上使用了 valine  没有头像

### ISSUE THREAD

**Issue by kkrepocom** [xCss/Valine-docs#71]
1、请求字体失败
https://fonts.loli.net/css?family=Rubik
2、
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/43947662/203514825-0487bf7d-2b9e-4c38-b360-a3e22ef072ac.png">

loli.net 这个网站现在不能用了吧？可以换个资源网站吗？

**Comment by xCss** [comment]
参考 #69
