### ISSUE TITLE
为什么无法提交评论

### ISSUE THREAD

**Issue by wsmdn** [xCss/Valine-docs#77]
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
us.leancloud.cn/1.1/classes/Comment:1 
        
        
        Failed to load resource: net::ERR_NAME_NOT_RESOLVED

**Comment by xCss** [comment]
请尝试以下操作：

- 1. 检查当前版本是否为最新版本v1.5.1
- 2. 参考：https://blog.csdn.net/hubojing/article/details/121770387
