### ISSUE TITLE
valine 1.5.1版本 尝试加入qq邮箱获取头像导致无法显示评论

### ISSUE THREAD

**Issue by windeling** [xCss/Valine-docs#78]
描述：
在采用valine 1.5.1版本后，发现只能通过昵称来获得qq头像，并且不能拉取qq昵称，想要加入通过qq邮箱来拉取头像的功能。

异常：
```
var qq_img = E.cdn+(0,s.default)(n.get("mail"))+E.params;
                    if (t.get("mail").indexOf("@qq.com") >= 0) {
                        var prefix = t.get("mail").replace(/@.*/, "");//前缀
                        var pattern = /^\d+$/g;  //正则表达式
                        var result = prefix.match(pattern);//match 是匹配的意思
                        if (result !== null) {
                            qq_img = "//q2.qlogo.cn/g?b=qq&nk=" + prefix + "&s=100";
                        }
                    }
```
在加入以上这段代码后，评论区崩溃了，无法加载出任何评论。
![image](https://github.com/xCss/Valine-docs/assets/142467582/488b3872-ecf2-4080-ac19-995aee4f4eec)
如上图所示，只显示出{}

推测：
采用的是1.4.1版本的代码控制，由于其图床API不可用转到1.5.1，发现各个字母均有变化。

恳请作者大大指教。

**Comment by BoredLiam** [comment]
在1.5.1版本中`f = $.hide ? "" : e.cfg.enableQQ && t.get("QQAvatar") ? (0, C.default)('<img class="vimg" src="' + j(t.get("QQAvatar")) + '" referrerPolicy="no-referrer"/>') : '<img class="vimg" src="' + ($.cdn + (0, u.default)(t.get("mail")) + $.params) + '">',`这段中 src中间部分由`E.cdn+(0,s.default)(n.get("mail"))+E.params;`更改为`$.cdn + (0, u.default)(t.get("mail")) + $.params`，将代码首句更改为`var qq_img = $.cdn + (0, u.default)(t.get("mail")) + $.params`即可
